name: CI

on:
  push:
  pull_request:
  # Also allow running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  unit-tests-single:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out reactor-c repository
        uses: actions/checkout@v2
      
      - name: Run the single-threaded unit tests
        run: |
          mkdir build
          cd build
          cmake .. -UNUMBER_OF_WORKERS
          cmake --build .
          make test

  unit-tests-multi:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out reactor-c repository
        uses: actions/checkout@v2
      
      - name: Run the multi-threaded unit tests
        run: |
          mkdir build
          cd build
          cmake .. -DNUMBER_OF_WORKERS=2
          cmake --build .
          make test

  fetch-lf:
    uses: lf-lang/lingua-franca/.github/workflows/extract-ref.yml@ci
    with:
      file: 'lingua-franca-ref.txt'
  
  lf-tests:
    needs: fetch-lf
    uses: lf-lang/lingua-franca/.github/workflows/c-tests.yml@master
    with:
      runtime-ref: ${{ github.ref }}
      compiler-ref: ${{ needs.fetch-lf.outputs.ref }}
