name: Unit tests

on:
  workflow_call:
    inputs:
      cmake-args:
        description: Arguments to pass to cmake
        type: string
        required: false
jobs:
  run:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out reactor-c repository
        uses: actions/checkout@v2

      - name: Build unit tests${{ inputs.cmake-args }}
        run: |
          mkdir build
          cd build
          cmake .. ${{ inputs.cmake-args }}
          cmake --build .
      - name: Run unit tests with sudo. (Needed for changing prio/policy)
        run: sudo make test
        if: matrix.platform == 'ubuntu-latest'
      - name: Run unit tests normal.
        run: cd build && make test
        if: matrix.platform != 'ubuntu-latest'
          
