name: User-requested benchmarks

on:
  issue_comment:
    types: [created]
  push:  # TODO: Remove this when this is in the default branch.
  workflow_dispatch:

env:  # TODO: Do not hard-code these!
  PR_NUMBER: 91
  SCHEDULER: NP
  FEATURE_BRANCH: automated-full-benchmark

permissions:
  contents: write
  pull-requests: write

jobs:
  run_benchmarks:
    runs-on: ubuntu-latest
    name: Post benchmark results in a PR.
    steps:
      - name: Checkout benchmark repository
        uses: actions/checkout@v2
        with:
          repository: lf-lang/benchmarks-lingua-franca
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          ref: automated-full-benchmark # FIXME: delete this line after merge

      - name: Checkout reactor-c
        uses: actions/checkout@v2
        with:
          repository: lf-lang/reactor-c
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # It will be necessary to push to this repo
          ref: graphics
          path: reactor-c

      - name: Set up workspace
        uses: lf-lang/reactor-c/.github/actions/set-up-workspace@automated-full-benchmark

      - name: Run C Benchmarks (feature branch)
        id: benchmarks-feature
        uses: lf-lang/reactor-c/.github/actions/run-benchmarks@automated-full-benchmark
        with:
          scheduler: ${{ env.SCHEDULER }}
          runtime-ref: ${{ env.FEATURE_BRANCH }}

      - name: Run C Benchmarks (main branch)
        id: benchmarks-main
        uses: lf-lang/reactor-c/.github/actions/run-benchmarks@automated-full-benchmark
        with:
          scheduler: GEDF_NP,NP,adaptive
          runtime-ref: main

      - name: Make figure
        run: |
          OUTPUT_DIR=images/$(date -I)
          echo "Figure will be created in $OUTPUT_DIR"
          SHA=${{ github.sha }}
          OUTPUT_FILE=$OUTPUT_DIR/$SCHEDULER-$FEATURE_BRANCH-${SHA:0:7}.png
          echo "Figure will be named $OUTPUT_FILE"
          mkdir -p reactor-c/$OUTPUT_DIR
          ./runner/make-graphics.py ${{ steps.benchmarks-feature.outputs.output-file }} \
            ${{ steps.benchmarks-main.outputs.output-file }} reactor-c/$OUTPUT_FILE
          echo "::set-output name=output-file::$OUTPUT_FILE"
        shell: bash
        id: figure

      - name: Commit figure
        run: |
          cd reactor-c
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch
          git add ${{ steps.figure.outputs.output-file }}
          git commit -m "benchmark ${{ github.sha }}"
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | \
            xargs -L1 git config --unset-all
          git push https://token:${{ secrets.GITHUB_TOKEN }}@github.com/lf-lang/reactor-c.git
          cd ..
        shell: bash

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ![Visualization of the benchmark results.](https://raw.githubusercontent.com/lf-lang/reactor-c/graphics/${{ steps.figure.outputs.output-file }})
          pr_number: ${{ env.PR_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
