name: User-requested benchmarks

on:
  issue_comment:
    types: [created]
  push:  # TODO: Remove this when this is in the default branch.
  workflow_dispatch:

env:  # TODO: Do not hard-code these!
  PR_NUMBER: 91
  SCHEDULER: NP
  FEATURE_BRANCH: automated-full-benchmark

permissions:
  contents: write
  pull-requests: write

jobs:
  run_benchmarks:
    runs-on: ubuntu-latest
    name: Post benchmark results in a PR.
    steps:
      - name: Checkout benchmark repository
        uses: actions/checkout@v2
        with:
          repository: lf-lang/benchmarks-lingua-franca
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          ref: automated-full-benchmark  # FIXME: delete this line after merge

      - name: Checkout reactor-c
        uses: actions/checkout@v2
        with:
          repository: lf-lang/reactor-c
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # It will be necessary to push to this repo
          ref: graphics
          path: reactor-c

      - name: Set up workspace
        uses: lf-lang/reactor-c/.github/actions/set-up-workspace@automated-full-benchmark

      - name: Run Benchmarks
        id: run-benchmarks
        uses: lf-lang/reactor-c/.github/actions/run-benchmarks-all-runtime-versions@automated-full-benchmark
        with:
          scheduler: ${{ env.SCHEDULER }}
          feature-branch: ${{ env.FEATURE_BRANCH }}

      - name: Visualize, Save, and Upload
        uses: lf-lang/reactor-c/.github/actions/visualize-save-upload@automated-full-benchmark
        with:
          csv-files: ${{ steps.run-benchmarks.outputs.output-files }}
          token: ${{ secrets.GITHUB_TOKEN }}  # FIXME: Should be a PAT
