name: User-requested benchmarks
on:
  issue_comment:
    types: [created]
  push:  # TODO: Remove this when this is in the default branch.
  workflow_dispatch:
    inputs:
      pr_number:
        required: true
        type: number
jobs:
  run_benchmarks:
    runs-on: ubuntu-latest
    name: Post benchmark results in a PR.
    steps:
      - name: Checkout benchmark repository
        uses: actions/checkout@v2
        with:
          repository: lf-lang/benchmarks-lingua-franca
          ref: cb # FIXME: delete this line after merge

      - name: Set up workspace
        uses: lf-lang/reactor-c/.github/actions/set-up-workspace@continuous-benchmarking

      - name: Run C Benchmarks
        # run: |
        #   ./runner/run_benchmark.py -m continue_on_error=True iterations=12 \
        #     benchmark="glob(*)" target=lf-c size=fast \
        #     target.params.scheduler=GEDF_NP,NP,adaptive threads=1,3,6,12,24
        run: |  # DEBUG
          ./runner/run_benchmark.py -m continue_on_error=True iterations=12 \
            benchmark="savina_parallelism_recmatmul" target=lf-c size=fast \
            target.params.scheduler=NP,adaptive threads=1,3,0
        shell: bash

      - name: Collect benchmark results
        run: |
          ./runner/collect_results.py latest latest-benchmark-results.csv
        shell: bash

      - name: Checkout repository for saving graphics
        uses: actions/checkout@v2
        with:
          repository: lf-lang/benchmarks-lingua-franca
          ref: graphics
          path: graphics-repo
          fetch-depth: 0  # History is required for push

      - name: Make figure
        run: |
          OUTPUT_DIR=runner/images/$(date -I)
          SHA=${{ github.sha }}
          OUTPUT_FILE=$OUTPUT_DIR/${SHA:0:7}.png
          mkdir -p graphics-repo/$OUTPUT_DIR
          ./runner/make-graphics.py latest-benchmark-results.csv graphics-repo/$OUTPUT_FILE
          echo "::set-output name=output_file::$OUTPUT_FILE"
        shell: bash
        id: figure

      - name: Commit figure
        run: |
          cd graphics-repo
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add ${{ steps.figure.outputs.OUTPUT_FILE }}
          git commit -m "benchmark ${{ github.sha }}"

      - name: Push figure
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: graphics

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ![Visualization of the benchmark results.](https://raw.githubusercontent.com/lf-lang/benchmarks-lingua-franca/graphics/${{ steps.figure.outputs.OUTPUT_FILE }})
          pr_number: 51 # ${{ inputs.pr_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
